language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - pip install -e .
    - pip install coveralls

script:
    - coverage run --source=Authda setup.py test

after_success:
    coveralls

notifications:
    email: false
